### ISSUE TITLE
Implement device authorization grant?

### ISSUE THREAD

**Issue by arianvp** [caos/oidc#141]
**Is your feature request related to a problem? Please describe.**
I want to authenticate my smart device which has no web browser with my phone.  The https://oauth.net/2/device-flow/ flow fixes this.

**Describe the solution you'd like**
Implement the https://oauth.net/2/device-flow/ flow

**Describe alternatives you've considered**
none

**Additional context**
https://oauth.net/2/device-flow/

**Comment by livio-a** [comment]
Hey @arianvp 

We definitely have it on the list for our OP implementation ZTIADEL(https://docs.zitadel.ch/docs/apis/openidoauth/grant-types) but forgot to list it here in the readme.

You would be more interested in the RP part, right?

**Comment by arianvp** [comment]
Actually interested in both

**Comment by livio-a** [comment]
It would certainly be a nice enhancement for ZITADEL as well, but to be honest, it's not high on the priority list right now.

Would you consider implementing one part or even both of them? 😃

**Comment by ovk** [comment]
I would be very interested in having device auth as well, as this is a hard requirement for our use-case.

**Comment by vanpelt** [comment]
💯  plus one.  Good to know I'm not the only one excited about this.

**Comment by braginini** [comment]
Same here. We'd love to see this feature implemented.
The only blocker for us not to go with zitadel at https://github.com/netbirdio/netbird

**Comment by fforootd** [comment]
> The only blocker for us not to go with zitadel at https://github.com/netbirdio/netbird

I like to hear about this 🥰

@hifabienne @livio-a let's discuss this again. Maybe it's time to solve this now. 😜

**Comment by livio-a** [comment]
I suggest that we take a look at it at one of the two meetings tomorrow.

**Comment by braginini** [comment]
FYI: We've just merged generic OIDC support in NetBird. Will be testing integration with Zitadel soon. @livio-a did you have any progress on the device flow?
https://github.com/netbirdio/dashboard/issues/9#issuecomment-1195553918

**Comment by fforootd** [comment]
@braginini love to hear this

Let me chat with @hifabienne and @livio-a on how to schedule this.
We are close to release ZITADEL v2 and afterwards some of our stuff might have time to look at this.

**Comment by braginini** [comment]
Hey guys, any progress here?

**Comment by hifabienne** [comment]
Hi @braginini 

Sorry we have not yet started with this. And currently we can't tell you a specific time when this will be finished, since we still have some other features that are higher in priority. 
We still think that this is something we like to implement soon.

Also PRs are highly appreciated. 😃

**Comment by mffap** [comment]
@hifabienne this seems to be the blocker for the [sovereign cloud stack](https://scs.community). Their IAM workgroup is [currently evaluating](https://input.osb-alliance.de/p/2023-scs-sig-iam) ZITADEL as IAM component. Would be great, if you could take this into consideration for planning. I will get more information on 2023-01-16, if SCS would be able to contribute.

**Comment by hifabienne** [comment]
I have created a user story according to this to be able to take it into our sprint planning, please subscribe to the following issue to get the updates on the state: https://github.com/zitadel/oidc/issues/264

**Comment by fforootd** [comment]
Just to raise some expectations 😁 https://github.com/zitadel/oidc/pull/285

**Comment by muhlemmer** [comment]
Closing as done in #285
